user = {'u_id' : 0, 'email' : 0, 'name_first' : 0, 'name_last' : 0, 'handle_str' : 0}
users = {'users': []} # list of different user
message = {'message_id' : 0, 'u_id' : 0, 'message' : 0, 'time_created' : 0}
messages = {'messages':[]} # list of different message
channel = {'channel_id' : 0, 'name' : 0}
channels = {'channels':[]} # list of different channel
member = {'u_id' : 0, 'name_first' : 0, 'name_last' : 0}
channel_info = {'name' : 0, 'owner_members' : [], 'name_last' : []}
channels_info = {'channels_info':[]} # list of different channels info
